### ISSUE TITLE
Add Tour End Date (TED) information to position card

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1002]
As a Bidder
I want to see the 'Start Date' (TED == Tour End Date) of the position
so that I can evaluate my search

## Acceptance Criteria
- Visualization of the Estimated End Date (EED) of a position

## Findings
Capsule descriptions should help people skim through positions

## Recommendation
Provide Bidders the most needed data

**Comment by krisdelacruz** [comment]
Continue to use TED for language

**Comment by krisdelacruz** [comment]
Content style guide* consistency on wording.

**Comment by mjoyce91** [comment]
@krisdelacruz @afrasier - We have the tour end date, but we don't have the estimated start date, correct?

**Comment by krisdelacruz** [comment]
Tour end date = is the end of the incumbents tour.

In which case is the “estimated start date” for the new bidder. But we don’t want to say “estimated” I believe we just want to say “Tour End Date”

**Comment by afrasier** [comment]
We calculate an incumbents "estimated end date" based on their start date + tour of duty; the "end_date" is only set when the assignment is completed or curtailed.

**Comment by mjoyce91** [comment]
Okay, so while we currently already have the TED (Tour End Date) on the position details for the incumbent, the point of this story is to display the end date for the next person going into this position? Which would just be TOD + TED.

**Comment by esgoodman** [comment]
I rewrote the original comment to try to answer your question, @mjoyce91. What bidders need is the month/year when the position will become open -- e.g., when the incumbent is supposed to leave. Bidders interested in the position need to calculate whether they can arrive within a month of that date, depending on travel arrangements, training, and other logistics. 

TED - Tour End Date - is the month/year when the incumbent is supposed to depart. That's what the bidder is using for their personal calculations. Our goal with this story is to help the bidder _quickly_ diagnose whether the logistics will work for any given position...or not. 

Unfortunately, we can't automate that calculation because of all the background contingencies: training needs, leave needs, whether the base is inclined to be flexible, etc. So we just have to put make the month/date of departure very visible to the bidder. 

@krisdelacruz, we might need to rewrite this issue.

**Comment by krisdelacruz** [comment]
@esgoodman On it! On the homepage redesign #1206 I'm working @shanzasubz to have "Tour End Date" as our first pass on locking down the logic around it.
