### ISSUE TITLE
Favoriting and Adding to Bid List feel unresponsive

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1351]
### Steps to reproduce the issue (please be as specific as possible)
Click on the ⭐️ icon to make a position a favorite (or not-favorite).
Click on Add to Bid List to add a position to your bid list.

### Expected behavior
The icon toggles to favorite/not-favorite state quickly.
The Add to Bid List button response quickly.

### Actual behavior
There is a noticeable delay in the icon state changing.

![favorite-slow](https://user-images.githubusercontent.com/697848/35627772-88e7776e-065f-11e8-9bc0-686781319fd3.gif)

### Suggestions
- What if we toggle the visual state _first_ before all the async actions are complete? Then, if the async actions fail (for any reason -- network error, too many in bid list, etc), we can revert the visual state. I'm not sure if that UX is great or not
- Show a spinner or some other loading state if the async actions take more than `THRESHOLD ms`

**Comment by mjoyce91** [comment]
Assigning to @Icemanbeta. The `Favorite` component should already contain an `isLoading` prop, so it should just be a matter of visualizing that prop, however we want. Maybe we can incorporate our fancy new TalentMAP spinner.

**Comment by Icemanbeta** [comment]
So spent a good amount of time trying to debug this one since the delay was definitely noticeable. Essentially with the redux pattern being implemented, all instances of `Favorite` components were being re-rendered in the list everytime you clicked, and not just the one being clicked.

I think I improved the speed quite a bit and it's timing feels more like the request call timing but if you guys feel like we should incorporate a loading UI, let me know, I'll go in for round 2. I think it's not bad but not sure how _sexy_ you guys want it.

I tried to convert this screen record to gif the gif kept coming out sped up. So here's the `.mov` file from my dropbox: https://www.dropbox.com/s/tf2z66jvtzo2p2g/favorite.mov?dl=0

**Comment by Icemanbeta** [comment]
@burgwyn Giphy Capture is pretty awesome lol.

@mjoyce91 
![favorite](https://user-images.githubusercontent.com/1786875/37311453-a770d166-261d-11e8-9b85-96fe6bd83e49.gif)
I can't seem to get rid of that focus outline from the spinner, I think it's because of rotation animation. There's no padding or size increase when comparing with the font-awesome container.

**Comment by mjoyce91** [comment]
I like the animation! Could we wrap the content of the link in a container with a min-height or padding?

**Comment by Icemanbeta** [comment]
@mjoyce91 Great idea! I kept thinking the opposite - trying to make the loading UI fit. New giphys!

![favorite-1](https://user-images.githubusercontent.com/1786875/37317746-11b2ad8c-263d-11e8-840a-0be8702e072e.gif)
![favorite-2](https://user-images.githubusercontent.com/1786875/37317750-1533b8a2-263d-11e8-9732-2af4f766cef0.gif)

**Comment by mjoyce91** [comment]
Looks great!
