### ISSUE TITLE
FSI usability testing plan

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1377]
As a TalentMAP team member, 
I need a plan for usability research with FS employees
So that I can carry out the research correctly

**Comment by jamiealbrecht** [comment]
Posting this in github this way so that it's a bit easier to share. What about something like this? I think there's definitely ways to improve some of the wording of this protocol (you all would know better than me), but hopefully this will get us started thinking about how we start some interviews soon.

**Content testing : highlighting exercise example protocol and script**

**Research questions**
- Is the homepage communicating what TalentMap is and what you can do here?
- Do people know what to do next?
- Is the website content clear?
- What questions do you users have?
- What words are confusing?

**Methods**
Paper-prototype content testing to measure whether the content is clear
3-5 in-person (or virtual if necessary) highlighting exercises

**Prep**
Print out pages of website content that you want to test
Get two different colored highlighters 
One color to highlight what makes sense or is helpful
One color to highlight what doesn’t makes sense or is confusing

**Script**
Hi there! Thanks for agreeing to talk to me — I really appreciate it. My name is [X] and I’m joined by my colleagues [X]. We’re working on improving aspects of the Foreign Service Talent Management System.

My goal today is to get feedback on some of our design ideas and the words we're using in them. I’m talking to people to see what makes sense and what’s confusing. 

Please note that this is not a test — there are no right or wrong answers! For this session, you are the expert, and you cannot be wrong.

Your participation is totally voluntary, and you’re free to end the interview at any time. With your permission, we’re going to record this session and take written notes. Is that okay?

The interview should take about 30 minutes. Do you have any questions? Let’s get started.

**Background questions**
Could you start by telling me about your experience bidding on foreign service positions? 
(This question may need to be worded differently, but this is just to get the idea for now)

**Highlighting activity**
Give the participant one section of the site content print-out, hand them two colors of highlighters, and ask them to read through the content and highlight it according to what makes sense and what doesn’t.

As they work through the pages: Ask follow-up questions as necessary, encourage them to follow their own process (i.e. it’s fine for them to do one read-through before they start highlighting), and respond to any questions with further discussion. If they're game — and there's time — ask if they'd be willing to try another section.

**Thank you (2 minutes)** 
Thank you so much for your time today. This is so valuable for our team. Is there anything I didn’t ask you about that you want to share with me? Thank you again!

**Comment by esgoodman** [comment]
@jamiealbrecht Can you move to wiki?

**Comment by krisdelacruz** [comment]
@cydneycappello This is a testing plan for the Search Results filters. Let's work together to get momentum on time, resources and approval from the clients.

**Comment by esgoodman** [comment]
@cydneycappello do you think you can move this to done?

**Comment by cydneycappello** [comment]
@esgoodman Yes I can. Moving this over to done now.

**Comment by esgoodman** [comment]
Testing completed!
