### ISSUE TITLE
COLA filter

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#219]
As a bidding employee,
I want to be able to add search criteria to include positions with COLA
for opportunities with COLA in my results list

Acceptance criteria:
- The bidder is able to indicate if they would like to include COLA opportunities
- By default, COLA opportunities are included in the positions results list
- The bidder must be able to read text content that asks if the bidder would like to include COLA opportunities (or some form of instruction)
- When indicated, the search includes a COLA filter

Definition of done:
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by mjoyce91** [comment]
@burgwyn  : @afrasier and I are looking at the new filters for this sprint. They all follow the logic of "Choose true to show all positions, choose false to show positions with no XYZ differential". Filtering on True is easy since you don't need to add any new parameters. but filtering on False is trickier since there are differentials with value `0` but also positions with `null` posts. I'm assuming we'd want to show both the positions with `0` as well as the positions with a `null` post. Should @afrasier build something out to account for that, or do we not want to worry about it since positions in the real data will always be associated with a post?

**Comment by burgwyn** [comment]
@mjoyce91 - I think we will be ok.  I take the story as "show me positions with a value > 0" for the true path.  The false path would be "don't include X filter in the search".

**Comment by mjoyce91** [comment]
@burgwyn - that clears things up. Thanks!

**Comment by esgoodman** [comment]
@burgwyn @mjoyce91 @krisdelacruz I think we should deprioritize these filters given results from usability tests with bidders.

**Comment by burgwyn** [comment]
Closing
