### ISSUE TITLE
Confirm valid State.gov email addresses

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#225]
Current assumption is that valid State emails end in @state.gov. However, there may be subdomains or alternate domains that are used for valid State employees. The regular expression that checks for a valid State email is in #120 .

**Comment by burgwyn** [comment]
@BrownCA5 - can you review?

**Comment by BrownCA5** [comment]
The assumption is correct.  Employees would have an @state.gov email address.  What you may be referring to is either when someone is on a detail (TDY), retired, or out on leave (i.e. LWOP).  In these cased, the person on detail should still have access to their state account, or would need access to that in order to access DoS systems.  The retired and LWOP people would use an external account for emailing, and not able to access DoS systems without an @state.gov account.

**Comment by burgwyn** [comment]
@mjoyce91 - the assumption has been validated
