### ISSUE TITLE
Discovery - Mapping Data

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#355]
Determine requirements, including:

- Internet access
- Provider and license
- Level of detail

**Comment by jseppi** [comment]
If we want to go with keeping country boundaries internally (ie, in our database), http://naturalearthdata.com/ is a good resource for public domain boundaries.

I am not aware of a US-government official dataset of world country boundaries, but that doesn't mean it doesn't exist somewhere. I wouldn't be surprised if DOS had one.

**Comment by patduggan** [comment]
Take a look at http://geonode.state.gov/ in general and http://geonode.state.gov/layers/geonode%3ALSIB7a_Gen in particular. Let me know if this works

**Comment by jseppi** [comment]
My initial thought for this is that we handle the mapping in-app rather than with a service, since that will obviate compliance and networking issues.

For implementation, that kinda depends. For the navigation map on the front page, we could go with something as simple as a TopoJSON file (converted from whatever the identified world boundaries dataset turns out to be) that is bundled with or otherwise served to the React app.

It gets a little more complicated factoring in the little map on the Position Details page, however. With that in mind it might make more sense to store the geospatial data in the database itself, maybe even bringing in the PostGIS extension.

**Comment by jseppi** [comment]
Database would also likely be an easier solution (than a bundled TopoJSON) for keeping boundaries up to date, since given the audience, it is probably important that country borders are correct.

**Comment by esgoodman** [comment]
@jseppi How will maps affect performance for low-bandwidth users?

**Comment by jseppi** [comment]
Definitely depends on the solution used and spatial resolution required, but regardless they'll have an impact.

For tile/slippy maps, there are potentially a lot of images being delivered to the client, which could be bad.

If we just need something as spatially-coarse as like country outlines, we could have something that's fairly bandwidth-light (ie, topojson, svg, etc).

**Comment by esgoodman** [comment]
@jseppi @burgwyn Can we close this since we've decided to take maps off the home page and the position details page?

**Comment by jseppi** [comment]
I'm good with closing it 👍 
If we ever bring back a map, we can open a new issue with hopefully more requirements known to aid in discovery.

**Comment by burgwyn** [comment]
Closing as this fuctionality has been removed from the current scope
