### ISSUE TITLE
Highlighted Positions by AO

### ISSUE THREAD

**Issue by afrasier** [18F/State-TalentMAP#466]
As a bureau authorized user,
I would like highlight a position
So that I can draw more attention to it

## Acceptance criteria
- A feed of highlighted positions from the API
- A way to see the feed of highlighted positions in the user interface

**Comment by mjoyce91** [comment]
Do we need to include CRUD actions in the acceptance criteria? The user story notes an action to highlight a position, but the acceptance criteria only mentions displaying them.

**Comment by mjoyce91** [comment]
Currently we have a "View More" link above the Highlighted Positions on the home page, but there is no filter for Highlighted positions. Do we want to include "Highlighted" as a boolean filter? Otherwise we'd be directing the user to a results page with highlighted positions, but no way to toggle between highlighted and non-highlighted positions. Otherwise, we can simply direct them to the base `/results` URL with no filters.

**Comment by afrasier** [comment]
I'm not sure, I'd need to add an extra filter to allow `?is_highlighted=true`
